### ISSUE TITLE
Unable to load beatmapsets

### ISSUE THREAD

**Issue by ABKQPO** [EVAST9919/lazer-swing#5]
```

2024-11-17 13:17:56 [verbose]: Song select updating selection with beatmap: Junk - Yellow Smile (bms edit) (Daycore) [Easy] 5f1520a3-9c89-4897-ac1c-3db48a7e4cdc ruleset:Sentakki
2024-11-17 13:17:56 [verbose]: Song select changing beatmap from "cYsmix - triangles (peppy) [peppy]" to "Junk - Yellow Smile (bms edit) (Daycore) [Easy]"
2024-11-17 13:17:56 [verbose]: Game-wide working beatmap updated to Junk - Yellow Smile (bms edit) (Daycore) [Easy]
2024-11-17 13:17:56 [verbose]: Song select working beatmap updated to Junk - Yellow Smile (bms edit) (Daycore) [Easy]
2024-11-17 13:17:56 [verbose]: Song select decided to ensurePlayingSelected
2024-11-17 13:17:56 [verbose]: 🌅 Global background change queued
2024-11-17 13:17:57 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:57 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:57 [verbose]: ⚠️ Failed to calculate beatmap difficulty
2024-11-17 13:17:57 [verbose]: 
2024-11-17 13:17:57 [verbose]: This error has been automatically reported to the devs.
2024-11-17 13:17:57 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:57 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:57 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:57 [verbose]: ⚠️ Failed to calculate beatmap difficulty
2024-11-17 13:17:57 [verbose]: 
2024-11-17 13:17:57 [verbose]: This error has been automatically reported to the devs.
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [verbose]: ⚠️ Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [verbose]: 
2024-11-17 13:17:58 [verbose]: This error has been automatically reported to the devs.
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [verbose]: ⚠️ Subsequent messages have been logged. Click to view log files.
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [verbose]: Song select updating selection with beatmap: Junk - Yellow Smile (bms edit) (Daycore) [Easy] 5f1520a3-9c89-4897-ac1c-3db48a7e4cdc ruleset:Swing
2024-11-17 13:17:58 [verbose]: decoupled ruleset transferred ("sentakki" -> "Swing")
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: Could not load beatmap successfully!
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods)
2024-11-17 13:17:58 [error]: at osu.Game.Screens.Select.BeatmapInfoWedge.WedgeInfoText.addInfoLabels()
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:17:58 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:17:58 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:18:04 [verbose]: 📺 OsuScreenStack#269(depth:4) suspended PlaySongSelect#496 (waiting on PlayerLoader#308)
2024-11-17 13:18:04 [verbose]: 📺 OsuScreenStack#269(depth:5) loading PlayerLoader#308
2024-11-17 13:18:04 [error]: Failed to calculate beatmap difficulty
2024-11-17 13:18:04 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:18:04 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:18:04 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods)
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.preProcess(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Difficulty.DifficultyCalculator.Calculate(IEnumerable`1 mods, CancellationToken cancellationToken)
2024-11-17 13:18:04 [error]: at osu.Game.Beatmaps.BeatmapDifficultyCache.computeDifficulty(DifficultyCacheLookup& key, CancellationToken cancellationToken)
2024-11-17 13:18:04 [verbose]: 📺 OsuScreenStack#269(depth:5) entered PlayerLoader#308
2024-11-17 13:18:04 [error]: Could not load beatmap successfully!
2024-11-17 13:18:04 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.updateNestedSamples()
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Swing.Objects.Hold.CreateNestedHitObjects(CancellationToken cancellationToken)
2024-11-17 13:18:04 [error]: at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
2024-11-17 13:18:04 [error]: at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(IRulesetInfo ruleset, IReadOnlyList`1 mods, CancellationToken token)
2024-11-17 13:18:04 [error]: at osu.Game.Screens.Play.Player.loadPlayableBeatmap(Mod[] gameplayMods, CancellationToken cancellationToken)
```

**Comment by EVAST9919** [comment]
Fixed in [latest update](https://github.com/EVAST9919/lazer-swing/releases/tag/2024.1117.0)
